name: XIV Rus

project:
  version: Команда XIV Rus НЕ связана со SQUARE ENIX ни в каком виде или форме. Представленный командой контент не является официальным и не претендует на интерпретацию мнений или взглядов SQUARE ENIX.
  description: Неофициальная русская локализация FINAL FANTASY XIV
  download_url: https://xivrus.ru/download
  download_text: Скачать

plugins:
  - jekyll-remote-theme

ui:
  mode: 'dark' # 'auto', 'dark', 'light'

# Build settings
remote_theme: xivrus/xivrus-theme
markdown: kramdown
kramdown:
  parse_block_html: true
